blank_issues_enabled: true
contact_links:
  - name: 🔒 Security Issue
    url: https://github.com/ivi374forivi/.github/security/advisories/new
    about: Please report security vulnerabilities privately
