blank_issues_enabled: false
contact_links:
  - name: 🔒 Security Issue
    url: https://github.com/ivi374forivi/.github/security/advisories/new
    about: Please report security vulnerabilities privately
  - name: 💬 GitHub Discussions
    url: https://github.com/orgs/ivi374forivi/discussions
    about: Ask questions and discuss with the community
  - name: 📖 Documentation
    url: https://github.com/ivi374forivi
    about: Read the documentation and guides
