blank_issues_enabled: false
contact_links:
  - name: 💬 Community Support
    url: https://github.com/ivi374forivi/.github/discussions
    about: Ask questions and discuss with the community
  - name: 🔒 Security Issue
    url: https://github.com/ivi374forivi/.github/security
    about: Please report security vulnerabilities privately
