name: CI

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Run tests
      run: |
        echo "Add your test commands here"
        # npm test
        # pytest
        # go test ./...
    
    - name: Build
      run: |
        echo "Add your build commands here"
        # npm run build
        # go build
        # make build
